# Generated by Django 2.1 on 2018-08-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0002_pizza_base_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='base_cost_cents',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='base_type',
            field=models.CharField(choices=[('THIN', 'Thin and Crispy'), ('DEEP', 'Deep Pan'), ('STUFFED', 'Stuffed Crust')], default='DEEP', max_length=30),
        ),
    ]
