# Generated by Django 2.1 on 2018-08-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0003_auto_20180805_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='base_weight_grams',
            field=models.IntegerField(default=250),
        ),
    ]
