# Generated by Django 2.1 on 2018-08-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('name_on_menu', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('labour_cost_to_make', models.IntegerField()),
                ('margin_percent', models.IntegerField()),
            ],
            options={
                'ordering': ['name_on_menu'],
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('ingredient_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('colour', models.CharField(choices=[('BL', 'Black'), ('GR', 'Grey'), ('WH', 'White'), ('YE', 'Yellow'), ('BR', 'Brown'), ('PU', 'Purple'), ('GR', 'Green'), ('RE', 'Red'), ('BL', 'Blue')], max_length=2)),
                ('portion_weight', models.IntegerField()),
                ('portion_cost', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizza_shop.Topping'),
        ),
    ]
