# Generated by Django 2.1 on 2018-08-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hero Name', max_length=100, unique=True)),
                ('bio', models.TextField(help_text='Hero Bio')),
                ('picture', models.URLField(help_text='URL to headshot image')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
