# Generated by Django 2.1 on 2018-09-01 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
