# Generated by Django 2.1 on 2018-09-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_superhero_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='slug',
            new_name='hero_name_slug',
        ),
    ]
