# Generated by Django 2.1 on 2018-09-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_auto_20180901_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='hero_name_slug',
            new_name='slug',
        ),
    ]
