# Generated by Django 2.1 on 2018-08-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Author Name', max_length=30)),
                ('email', models.EmailField(help_text='Email Address', max_length=254, unique=True)),
                ('bio', models.TextField(help_text='Author Bio')),
                ('headshot_url', models.URLField(help_text='URL to headshot image')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_published', models.TimeField(help_text='Date Published', null=True)),
                ('date_created', models.TimeField(help_text='Date Created')),
                ('title', models.CharField(default='My Blog Post', help_text='Blog Title', max_length=255)),
                ('html_content', models.TextField(help_text='Blog HTML Content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
            options={
                'ordering': ('date_published',),
            },
        ),
    ]
