# Generated by Django 2.1 on 2018-08-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('date_published',), 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_published',
            field=models.TimeField(blank=True, help_text='Date Published'),
        ),
    ]
