# Generated by Django 2.1 on 2018-08-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180810_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_published',
            field=models.TimeField(blank=True, help_text='Date Published', null=True),
        ),
    ]
