# Generated by Django 2.1 on 2018-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180810_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateField(help_text='Date Created'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_published',
            field=models.DateField(blank=True, help_text='Date Published', null=True),
        ),
    ]
