# Generated by Django 2.1 on 2018-08-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180810_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateField(blank=True, help_text='Date Created', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='html_content',
            field=models.TextField(default='My Blog Content', help_text='Blog HTML Content'),
        ),
    ]
