# Generated by Django 2.1 on 2018-08-12 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180811_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 12, 0, 58, 46, 413225), help_text='Date Created'),
        ),
    ]
