# Generated by Django 2.1 on 2018-08-12 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180812_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 12, 0, 59, 11, 948035), help_text='Date Created'),
        ),
    ]
